version: "3.9"
services:
  first-task:
    build: .
    environment:
      SECRET_KEY: "roapjumping"
      PGX_CONN_STRING: "postgres://personuser:minovich12@postgres:5432/persondb"
    ports:
      - 8080:8080
    networks:
      - my-network
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "persondb"
      POSTGRES_USER: "personuser"
      POSTGRES_PASSWORD: "minovich12"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - 5432:5432
    networks:
      - my-network
  redis:
    image: redis
    environment:
      REDIS_PASSWORD: "minovich12"
      REDIS_CONN_STRING: "localhost:6379"
    ports:
      - 6379:6379
    networks:
      - my-network

networks:
  my-network: