version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "persondb"
      POSTGRES_USER: "personuser"
      POSTGRES_PASSWORD: "minovich12"
    ports:
      - "5432:5432"
