
curl -H 'Content-Type: application/json' \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODgxMzM0MDYsImlkIjoiOWE4YzFmMmItNDg2OC00ODI1LTgwZjUtMTZmNDg2OWEzNTU0In0.CaUIoxYy-BMH_IpoMuUtv3zvUdwoDmQn1DcC0pm3ePw" \
  -X POST \
  -d '{"salary":3500, "married":true, "profession":"gamer"}' \
  http://localhost:8080/persons
###
curl http://localhost:8080/persons/c4f21c39-2975-42f2-9686-abf4c2cf4750 \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODgxMzM0MDYsImlkIjoiOWE4YzFmMmItNDg2OC00ODI1LTgwZjUtMTZmNDg2OWEzNTU0In0.CaUIoxYy-BMH_IpoMuUtv3zvUdwoDmQn1DcC0pm3ePw"

###
curl http://localhost:8080/persondb

###
curl -X PUT \
  -H 'Content-Type: application/json' \
  # -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc3MTUyMDJ9.PD_t4lx8gDfjfMrlXDkYq_dwxt30F7ZtTSrRwEsIZRs" \
  -d '{"Salary":2000, "Married":true, "Profession":"trainer"}' \
  http://localhost:8080/persondb/ebd74a3d-2dc3-4642-aa2e-384499a98d1c
###

curl -X DELETE http://localhost:8080/persondb/a8fe07da-2e75-41fe-a7fb-4974e9f5a8da

###
curl -X POST \
  -H 'Content-Type: application/json' \
  -d {'"username":"Mfffn", "password":"minovich12"'} \
  http://localhost:8080/signUp
###
curl -X POST  \
  -H 'Content-Type: application/json' \
  -d {'"username":"Mfffn", "password":"minovich12"'} \
  http://localhost:8080/login

###
curl -X POST \
  -H 'Content-Type: application/json' \
  -d {'"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc3ODk0MDYsImlkIjoiZGE5ZDAxZjktZTE3My00MDI1LWE4OTYtZDgxMTJmNWUxMzczIn0.ljKzgqcx03GVVIX9I-WisjSqgrPgi6BRTccCquoAwMk", "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODgwNDc3MDYsImlkIjoiZGE5ZDAxZjktZTE3My00MDI1LWE4OTYtZDgxMTJmNWUxMzczIn0.lTIZ6YRamJmEDq-DIp520JiCp3HjBMELVFgfAWkh6J4"'} \
  http://localhost:8080/refresh
###
curl http://localhost:8080/downloadImage/andy.png
###
