
curl -H 'Content-Type: application/json' \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODgwNjMzMzMsImlkIjoiOWE4YzFmMmItNDg2OC00ODI1LTgwZjUtMTZmNDg2OWEzNTU0In0.z_p24NZa38mIfbeKGJHpiV9BHeCdZ8Qh1fClJxNRV7E" \
  -X POST \
  -d '{"salary":500, "married":true, "profession":"hockey player"}' \
  http://localhost:8080/persondb 
###
curl http://localhost:8080/persondb/aa715651-d339-45bb-83de-d2701b449094 \
###
curl http://localhost:8080/persondb

###
curl -X PUT \
  -H 'Content-Type: application/json' \
  # -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc3MTUyMDJ9.PD_t4lx8gDfjfMrlXDkYq_dwxt30F7ZtTSrRwEsIZRs" \
  -d '{"Salary":2000, "Married":true, "Profession":"trainer"}' \
  http://localhost:8080/persondb/ebd74a3d-2dc3-4642-aa2e-384499a98d1c
###

curl -X DELETE http://localhost:8080/persondb/a8fe07da-2e75-41fe-a7fb-4974e9f5a8da

###
curl -X POST \
  -H 'Content-Type: application/json' \
  -d {'"username":"Mfffn", "password":"minovich12"'} \
  http://localhost:8080/signUp
###
curl -X POST  \
  -H 'Content-Type: application/json' \
  -d {'"username":"Mfffn", "password":"minovich12"'} \
  http://localhost:8080/login

###
curl -X POST \
  -H 'Content-Type: application/json' \
  -d {'"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc3ODk0MDYsImlkIjoiZGE5ZDAxZjktZTE3My00MDI1LWE4OTYtZDgxMTJmNWUxMzczIn0.ljKzgqcx03GVVIX9I-WisjSqgrPgi6BRTccCquoAwMk", "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODgwNDc3MDYsImlkIjoiZGE5ZDAxZjktZTE3My00MDI1LWE4OTYtZDgxMTJmNWUxMzczIn0.lTIZ6YRamJmEDq-DIp520JiCp3HjBMELVFgfAWkh6J4"'} \
  http://localhost:8080/refresh
###
curl http://localhost:8080/downloadImage/andy.png
###
